version: '3.3'

services:
  server:
    build: .
    ports:
      - "8000:8000"
    entrypoint: /backend/server_entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - /tmp/postgres/data:/var/lib/postgresql/data
    container_name: postgres

  worker:
    build: .
    depends_on:
      - server
      - redis
    entrypoint: /backend/worker_entrypoint.sh

  redis:
    restart: unless-stopped
    image: redis
    container_name: redis
    volumes:
      - /tmp/redis/data:/data